/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as AuthenticatedAbonnementRouteImport } from './routes/_authenticated/abonnement'
import { Route as AuthenticatedCalendrierRouteImport } from './routes/_authenticated/calendrier'
import { Route as AuthenticatedCreerUnPostRouteImport } from './routes/_authenticated/creer-un-post'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIdeesDeContenuRouteImport } from './routes/_authenticated/idees-de-contenu'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedRepondreAuxAvisRouteImport } from './routes/_authenticated/repondre-aux-avis'
import { Route as ApiPublicWhopWebhookRouteImport } from './routes/api/public/whop-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAbonnementRoute = AuthenticatedAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendrierRoute = AuthenticatedCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreerUnPostRoute =
  AuthenticatedCreerUnPostRouteImport.update({
    id: '/creer-un-post',
    path: '/creer-un-post',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdeesDeContenuRoute =
  AuthenticatedIdeesDeContenuRouteImport.update({
    id: '/idees-de-contenu',
    path: '/idees-de-contenu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepondreAuxAvisRoute =
  AuthenticatedRepondreAuxAvisRouteImport.update({
    id: '/repondre-aux-avis',
    path: '/repondre-aux-avis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWhopWebhookRoute = ApiPublicWhopWebhookRouteImport.update({
  id: '/api/public/whop-webhook',
  path: '/api/public/whop-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/abonnement': typeof AuthenticatedAbonnementRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/creer-un-post': typeof AuthenticatedCreerUnPostRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/idees-de-contenu': typeof AuthenticatedIdeesDeContenuRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/repondre-aux-avis': typeof AuthenticatedRepondreAuxAvisRoute
  '/api/public/whop-webhook': typeof ApiPublicWhopWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/abonnement': typeof AuthenticatedAbonnementRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/creer-un-post': typeof AuthenticatedCreerUnPostRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/idees-de-contenu': typeof AuthenticatedIdeesDeContenuRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/repondre-aux-avis': typeof AuthenticatedRepondreAuxAvisRoute
  '/api/public/whop-webhook': typeof ApiPublicWhopWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/_authenticated/abonnement': typeof AuthenticatedAbonnementRoute
  '/_authenticated/calendrier': typeof AuthenticatedCalendrierRoute
  '/_authenticated/creer-un-post': typeof AuthenticatedCreerUnPostRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/idees-de-contenu': typeof AuthenticatedIdeesDeContenuRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/repondre-aux-avis': typeof AuthenticatedRepondreAuxAvisRoute
  '/api/public/whop-webhook': typeof ApiPublicWhopWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgu'
    | '/cgv'
    | '/confidentialite'
    | '/connexion'
    | '/inscription'
    | '/mentions-legales'
    | '/abonnement'
    | '/calendrier'
    | '/creer-un-post'
    | '/dashboard'
    | '/idees-de-contenu'
    | '/parametres'
    | '/repondre-aux-avis'
    | '/api/public/whop-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgu'
    | '/cgv'
    | '/confidentialite'
    | '/connexion'
    | '/inscription'
    | '/mentions-legales'
    | '/abonnement'
    | '/calendrier'
    | '/creer-un-post'
    | '/dashboard'
    | '/idees-de-contenu'
    | '/parametres'
    | '/repondre-aux-avis'
    | '/api/public/whop-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cgu'
    | '/cgv'
    | '/confidentialite'
    | '/connexion'
    | '/inscription'
    | '/mentions-legales'
    | '/_authenticated/abonnement'
    | '/_authenticated/calendrier'
    | '/_authenticated/creer-un-post'
    | '/_authenticated/dashboard'
    | '/_authenticated/idees-de-contenu'
    | '/_authenticated/parametres'
    | '/_authenticated/repondre-aux-avis'
    | '/api/public/whop-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CguRoute: typeof CguRoute
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ApiPublicWhopWebhookRoute: typeof ApiPublicWhopWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/abonnement': {
      id: '/_authenticated/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AuthenticatedAbonnementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendrier': {
      id: '/_authenticated/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof AuthenticatedCalendrierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creer-un-post': {
      id: '/_authenticated/creer-un-post'
      path: '/creer-un-post'
      fullPath: '/creer-un-post'
      preLoaderRoute: typeof AuthenticatedCreerUnPostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/idees-de-contenu': {
      id: '/_authenticated/idees-de-contenu'
      path: '/idees-de-contenu'
      fullPath: '/idees-de-contenu'
      preLoaderRoute: typeof AuthenticatedIdeesDeContenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repondre-aux-avis': {
      id: '/_authenticated/repondre-aux-avis'
      path: '/repondre-aux-avis'
      fullPath: '/repondre-aux-avis'
      preLoaderRoute: typeof AuthenticatedRepondreAuxAvisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whop-webhook': {
      id: '/api/public/whop-webhook'
      path: '/api/public/whop-webhook'
      fullPath: '/api/public/whop-webhook'
      preLoaderRoute: typeof ApiPublicWhopWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbonnementRoute: typeof AuthenticatedAbonnementRoute
  AuthenticatedCalendrierRoute: typeof AuthenticatedCalendrierRoute
  AuthenticatedCreerUnPostRoute: typeof AuthenticatedCreerUnPostRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIdeesDeContenuRoute: typeof AuthenticatedIdeesDeContenuRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedRepondreAuxAvisRoute: typeof AuthenticatedRepondreAuxAvisRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbonnementRoute: AuthenticatedAbonnementRoute,
  AuthenticatedCalendrierRoute: AuthenticatedCalendrierRoute,
  AuthenticatedCreerUnPostRoute: AuthenticatedCreerUnPostRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIdeesDeContenuRoute: AuthenticatedIdeesDeContenuRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedRepondreAuxAvisRoute: AuthenticatedRepondreAuxAvisRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CguRoute: CguRoute,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ApiPublicWhopWebhookRoute: ApiPublicWhopWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
